### ISSUE TITLE
exec: "aws": executable file not found in $PATH

### ISSUE THREAD

**Issue by Minkiu** [flathub/dev.skynomads.Seabird#21]
Hey there! Thanks for the app @jgillich (and packaging it as a flatpak) it's really nice.

The current flatpak doesn't seem to find the `aws`  command no matter what I try:
`exec: "aws": executable file not found in $PATH`

I've tried giving full access, as suggested in the docs, to the host to the app through Flatseal, it did not work, and when I went inside the shell with `flatpak run --command=bash` it did not find it at all, even though outside it was present in `/usr/bin/aws` and other binaries where visible with `ls /usr/bin`.

I've also tried being specific and doing `--filesystem=/usr/bin/aws`, it did not work, when entering the shell it `flatpak` complained about `/usr/bin` being reserved, but the behaviour was the same as above.

Lastly I tried installing the `awscli` on my `~/.local/bin`, it did not work, for this last attempt, I also opened a shell on the container to make sure that `which aws` does work:
```
Downloads/awscli-exe-linux-x86_64/aws on ☁️  (eu-west-1) 
❯ ./install -i ~/.local/aws-cli -b ~/.local/bin
You can now run: /home/minkiu/.local/bin/aws --version

Downloads/awscli-exe-linux-x86_64/aws on ☁️  (eu-west-1) 
❯ which aws
/home/minkiu/.local/bin/aws

Downloads/awscli-exe-linux-x86_64/aws on ☁️  (eu-west-1) 
❯ flatpak run --command=bash dev.skynomads.Seabird
[📦 dev.skynomads.Seabird aws]$ which aws
/home/minkiu/.local/bin/aws
[📦 dev.skynomads.Seabird aws]$ printenv PATH
/home/minkiu/.bun/bin:/home/minkiu/.cargo/bin:/home/minkiu/.local/bin:/home/minkiu/bin:/app/bin:/usr/bin
```

Any ideas what might be causing this? 
Thanks!

**Comment by jgillich** [comment]
`~/.local/bin` is mounted in the Flatpack, but you probably need to add it to the $PATH variable.

**Comment by jgillich** [comment]
(Bash loads your bash profile, but the app does not)

**Comment by Minkiu** [comment]
Hmm is this something that can be added on the manifest?

Anyhow I modified the `PATH` env var with Flatseal and set it to:
`PATH=/app/bin:/usr/bin:/home/minkiu/.local/bin`

And that does the trick, thanks!
